exports.usedHFUIIcon = [
    'refresh',
    'caret-down',
    'filter',
    'chevron-down',
    'chevron-up',
    'info-sign',
    'cross',
    'tick', // 对号
    'issue', // 感叹号
    'search',
    'time',
    'timeline-line-chart',
    'duplicate',
    'help',
    'small-cross',
    'warning-sign',
    'document-open',
    'trash',
    'eraser',
    'small-tick',
    'star-empty',
    'star',
    'small-plus',
    'small-minus',
    'settings',
    'tag',
    'eye-off',
    'more',
    'history',
]